version: '3.8'

services:
  frontend:
    container_name: nasa-hack-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
      # Prevent node_modules from being overwritten
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped
